### ISSUE TITLE
Server Crash on Latest Version

### ISSUE THREAD

**Issue by Rhodizzle** [cnaude/PurpleIRC-forge#2]
I've gotten this twice since the 17th:

```
java.lang.NullPointerException: Exception in server tick loop 
        at net.minecraft.entity.player.EntityPlayerMP.func_71114_r(EntityPlayerMP.java:971) 
        at com.cnaude.purpleirc.Utilities.ChatTokenizer.playerTokenizer(ChatTokenizer.java:285) 
        at com.cnaude.purpleirc.Utilities.ChatTokenizer.gameChatToIRCTokenizer(ChatTokenizer.java:218) 
        at com.cnaude.purpleirc.PurpleBot.gameQuit(PurpleBot.java:1096) 
        at com.cnaude.purpleirc.GameListeners.GamePlayerQuitListener.onPlayerLogout(GamePlayerQuitListener.java:53) 
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1005_GamePlayerQuitListener_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) 
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) 
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:555) 
        at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:318)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:633) 
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:158) 
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) 
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) 
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) 
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) 
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) 
```

Any ideas?

**Comment by cnaude** [comment]
Fixed in latest build. http://h.cnaude.org:8081/job/PurpleIRC-forge/
