### ISSUE TITLE
Please use serverSideOnly with @Mod

### ISSUE THREAD

**Issue by jikuja** [cnaude/PurpleIRC-forge#5]
I just tried your mod and got

```
java.lang.NoClassDefFoundError: net/minecraft/server/dedicated/DedicatedServer
    at net.minecraftforge.fml.server.FMLServerHandler.allowLogins(FMLServerHandler.java:260) ~[FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:290) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.dedicated.DedicatedServer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 4 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@790bbf73 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.9-12.16.0.1804-1.9.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 4 more
Caused by: java.lang.RuntimeException: Attempted to load class la for invalid side CLIENT
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49) ~[forge-1.9-12.16.0.1804-1.9.jar:?]
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.9-12.16.0.1804-1.9.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 4 more
```

Please, consider using `serverSideOnly` to disable mod load in client-side without crashing users' client. Also mention server-side only usage in first pages. Ref: https://github.com/MinecraftForge/MinecraftForge/commit/7269d2244914700dd5a7970a728bd043132f8746

**Comment by cnaude** [comment]
What version of Forge did you get this error on? Did you try this in single player mode or multiplayer mode?

**Comment by cnaude** [comment]
No response.
